import type { Metadata } from "next";
import "@/styles/globals.css";
import TopNav from "./_components/TopNav";
import Footer from "./_components/Footer";
import BottomNav from "./_components/BottomNav";
import { Suspense } from "react";
import { Language } from "@/lib/definitions";

export const metadata: Metadata = {
  title: "Netron",
  description: "Generated by create next app",
};

type Props = Readonly<{
  children: React.ReactNode;
  params: {
    lang: Language
  }
}>

export default function RootLayout(props: Props) {
  return (
    <>
      <TopNav lang={props.params.lang} />
      <Suspense>
        <div className="container prose min-w-full py-20">{props.children}</div>
      </Suspense>
      <Footer />
      <BottomNav />
    </>
  );
}
