import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"
import { Toaster } from "@/components/ui/sonner"
import "@/styles/globals.css";
// import { dir } from 'i18next'
import type { Language } from "@/lib/definitions";
import { languages } from "./i18n/settings";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Netron",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

type Props = Readonly<{
  children: React.ReactNode;
  params: {
    lang: Language
  }
}>

export default function RootLayout(props: Props) {
  return (
    <html lang={props.params.lang}>
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>
        {props.children}
        <Toaster position="top-right" closeButton />
      </body>
    </html>
  );
}
