import Breadcrumb from "@/app/netronAdmin/_components/Breadcrumb"
import Footer from "@/app/netronAdmin/_components/Footer"
import Sidebar from "@/app/netronAdmin/_components/Drawer"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex h-screen">
      <Sidebar />
      <div className="flex flex-col grow">
        <main className="grow px-8 pt-8 pb-0 flex flex-col">
          <Breadcrumb />
          <div className='grow flex flex-col gap-8 pt-2.5'>
            {children}
          </div>
        </main>
        <Footer />
      </div>
    </div>
  )
}
