import Breadcrumb from "@/components/netronAdmin/global/breadcrumb"
import Footer from "@/components/netronAdmin/global/footer"
import Sidebar from "@/components/netronAdmin/global/Drawer"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="flex h-screen">
      <Sidebar />
      <div className="flex flex-col grow">
        <main className="grow p-8 flex flex-col">
          <Breadcrumb />
          <div className='flex flex-col gap-8 pt-2.5'>
            {children}
          </div>
        </main>
        <Footer />
      </div>
    </div>
  )
}
