import type { Metadata } from "next";
import "@/styles/globals.css";
import TopNav from "@/app/(public)/_components/TopNav";
import Footer from "@/app/(public)/_components/Footer";
import BottomNav from "@/app/(public)/_components/BottomNav";

export const metadata: Metadata = {
  title: "Netron",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <TopNav />
      {children}
      <Footer />
      <BottomNav />
    </>
  );
}
