import type { Metadata } from "next";
import "@/styles/globals.css";
import TopNav from "@/components/(public)/global/top-nav";
import Footer from "@/components/(public)/global/footer";
import BottomNav from "@/components/(public)/global/bottom-nav";

export const metadata: Metadata = {
  title: "Netron",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <TopNav />
      {children}
      <Footer />
      <BottomNav />
    </>
  );
}
